### PR TITLE
A new era of Web-Components

### PR DESCRIPTION
**Pull request by Idzikowski-Casey**
A new monorepo architecture with several component libraries. `ui-components` now uses `sass/scss` for styles instead of `.styl` as well as updated `blueprintjs`.

### CODE REVIEW

**Comment by Idzikowski-Casey** [comment]
Probably yes, it looks like the form-components and data-components both
have package-lock files that didnt get sequester in a .gitignore.

**Comment by Idzikowski-Casey** [comment]
There are also some very long `JSON` files in the `data/macrostrat` directory. Maybe of the "1" liners are a single data value. I loaded one on the diff viewer and it was around 4,000 lines. I'm guessing that the data files are taking up the most room.

**Comment by Idzikowski-Casey** [comment]
The `all-columns.topo.json` file is `197,000` lines alone.

**Comment by davenquinn** [comment]
That data is generated and should probably just be omitted from the repo, or minified/gzipped.

Daven

**Pull request merged**
